// src/types/index.ts

export type Instituto =
  | "ICHC" | "InCor" | "IOT" | "IPQ" | "InRad" | "ICr"
  | "ICESP" | "IMREA" | "LIMs" | "IPer" | "IGS"
  | "Outros";

export type Role = "employee" | "coordinator" | "admin";

export interface UserPersonalizations {
  colorTheme?: string;
  statusEmoji?: string;
  customTitle?: string;
}

export interface QuizAttempt {
  moduleId: string;
  attempts: number;
  passed: boolean;
  score: number;
}

export interface OnboardingFeedback {
  rating: number;
  message: string;
  submittedAt: number;
}

// ✅ ADICIONADO: Interface para os detalhes da conclusão que estava faltando.
export interface CompletionDetails {
  completedAt: number;
  daysToComplete: number;
  wasOverdue: boolean;
}

export interface User {
  uid: string;
  email: string;
  displayName: string;
  photoURL: string | null;
  instituto: Instituto;
  role: Role;
  profession: string;
  bio: string;
  points: number;
  badges: string[];
  completedModules: string[];
  quizAttempts: Record<string, QuizAttempt>;
  createdAt: number;
  lastAccess: number | any;
  profileCompleted: boolean;
  onboardingCompleted: boolean;
  currentRank: number;
  instituteRank: number;
  welcomeModalSeen: boolean;
  tourSeen: boolean;
  personalizations: UserPersonalizations;

  // ✅ CORREÇÃO: A tipagem agora aceita `null` para evitar o erro de `undefined`.
  onboardingFeedback?: OnboardingFeedback | null; 
  completionDetails?: CompletionDetails | null;
}

// O restante do arquivo (Module, Notification, etc.) permanece o mesmo...
export interface Module {
  id: string;
  title: string;
  description: string;
  order: number;
  points: number;
  category: string;
  estimatedMinutes: number;
  imageUrl?: string;
  isRequired: boolean;
  url?: string; // Campo para links externos
}

export interface Notification {
  id: string;
  userId: string;
  type: 'module_completion' | 'badge_earned' | 'feedback_received' | 'admin_message';
  message: string;
  read: boolean;
  createdAt: number;
  link?: string;
}

export interface Certificate {
  id: string;
  userId: string;
  moduleId: string;
  moduleTitle: string;
  completionDate: number;
  certificateNumber: string;
}

export interface Badge {
  id: string;
  name: string;
  description: string;
  icon: string;
  category: 'completion' | 'engagement' | 'special';
  points: number;
}

export interface InstitutoConfig {
  name: Instituto;
  fullName: string;
  logo: string;
  color: string;
}

export const INSTITUTOS_ARRAY: Instituto[] = [
  "ICHC", "InCor", "IOT", "IPQ", "InRad", "ICr",
  "ICESP", "IMREA", "LIMs", "IPer", "IGS", "Outros"
];

export const PROFESSIONS_ARRAY: string[] = [
  "ADMINISTRADOR", "ADVOGADO", "ADVOGADO JR", "ADVOGADO LGPD", "ADVOGADO PL", "ADVOGADO SR", "AGENTE ADMINISTRATIVO",
  "AGENTE COMUNITARIO DE SAUDE", "AGENTE DE SAUDE", "AGENTE OPERACIONAL", "AGENTE TECNICO DE ASSISTENCIA A SAUDE",
  "AGENTE TECNICO DE SAUDE", "AGENTE TECNICO SAUDE", "ANALISTA FAT HOSPITALAR JR", "ANALISTA FAT HOSPITALAR PL",
  "ANALISTA FAT HOSPITALAR SR", "ANALISTA ADM DE INFORMACOES MASTER", "ANALISTA ADMINISTRATIVO", "ANALISTA ADMINISTRATIVO JR",
  "ANALISTA BANCO DADOS JR", "ANALISTA BANCO DADOS SR", "ANALISTA CAPACITACAO PL", "ANALISTA COMERCIAL",
  "ANALISTA COMUNICACAO", "ANALISTA COMUNICACAO SR", "ANALISTA CONTABIL", "ANALISTA CONTABIL JR", "ANALISTA CONTRATOS",
  "ANALISTA DADOS E PESQUISA PL", "ANALISTA DE BANCO DE DADOS MS", "ANALISTA DE COMUNICAÇÃO E MARKETING",
  "ANALISTA DE CONTAS HOSPITALARES", "ANALISTA DE DIVERSIDADE E INCLUSAO", "ANALISTA DE FATURAMENTO", "ANALISTA DE GLOSA",
  "ANALISTA DE HOLTER", "ANALISTA DE LABORATORIO", "ANALISTA DE NEGOCIOS JR", "ANALISTA DE NEGOCIOS PL",
  "ANALISTA DE NEGOCIOS SR", "ANALISTA DE PROJETOS", "ANALISTA DE QUALIDADE", "ANALISTA DE RECURSOS HUMANOS",
  "ANALISTA DE SISTEMAS JR", "ANALISTA DE SISTEMAS MS", "ANALISTA DE SISTEMAS PL", "ANALISTA DE SISTEMAS SR",
  "ANALISTA DE SUPORTE AO USUARIO MASTER", "ANALISTA DE SUPORTE AO USUARIO PL", "ANALISTA DE SUPORTE TECNICO JR",
  "ANALISTA DE SUPORTE TECNICO PL", "ANALISTA DE SUPORTE TECNICO SR", "ANALISTA DE TECNOLOGIA", "ANALISTA DE TESOURARIA",
  "ANALISTA DESENVOLVIMENTO CG's JR", "ANALISTA DESENVOLVIMENTO ORGANIZACIONAL JR", "ANALISTA ECONOMICO FINANCEIRO",
  "ANALISTA FATURAMENTO HOSPITALAR JR", "ANALISTA FATURAMENTO HOSPITALAR PL", "ANALISTA FINANCEIRO JR",
  "ANALISTA FINANCEIRO PL", "ANALISTA FINANCEIRO SR", "ANALISTA FISCAL", "ANALISTA FUNCIONAL PL",
  "ANALISTA FUNCIONAL SR", "ANALISTA FUNCIONAL TR", "ANALISTA LABORATORIO", "ANALISTA PROGRAMADOR SISTEMAS SR",
  "ANALISTA PROJETO PL", "ANALISTA PROJETOS EM PESQUISA SR", "ANALISTA PROJETOS JR", "ANALISTA PROJETOS PL",
  "ANALISTA PROJETOS SR", "ANALISTA RECURSOS HUMANOS", "ANALISTA RECURSOS HUMANOS JR", "ANALISTA RECURSOS HUMANOS PL",
  "ANALISTA SAUDE SUPLEMENTAR PL", "ANALISTA SISTEMAS JR", "ANALISTA SISTEMAS PL", "ANALISTA SISTEMAS SR",
  "ANALISTA SOCIOCULTURAL", "ANALISTA SUP TELEP JR", "ANALISTA SUPORTE ACADEMICO PL", "ANALISTA SUPORTE TECNICO PL",
  "ANALISTA SUPORTE TECNICO SR", "ANALISTA TECNICO", "APRENDIZ DE ASSISTENTE ADMINISTRATIVO", "ARQUITETO",
  "ASCENSORISTA", "ASSESSOR", "ASSESSOR ADMINISTRATIVO", "ASSESSOR CIENTIFICO EDUCACIONAL", "ASSESSOR COMUNICACAO",
  "ASSESSOR DE ENSINO", "ASSESSOR DE IMPRENSA", "ASSESSOR DE PESQUISA JR", "ASSESSOR DE QUALIDADE",
  "ASSESSOR DE RELACOES INSTITUCIONAIS", "ASSESSOR I", "ASSESSOR IMPRENSA", "ASSESSOR IMPRENSA SR",
  "ASSESSOR TÉCNICO EM SAÚDE PÚBLICA I", "ASSESSOR TÉCNICO EM SAÚDE PÚBLICA II", "ASSESSOR TÉCNICO EM SAÚDE PÚBLICA III",
  "ASSESSOR TÉCNICO I", "ASSESSOR TÉCNICO II", "ASSESSOR TÉCNICO III", "ASSESSOR TÉCNICO IV", "ASSESSOR TÉCNICO VI",
  "ASSISTENTE ADMINISTRATIVO", "ASSISTENTE ADMINISTRATIVO HOSPITALAR", "ASSISTENTE COMERCIAL", "ASSISTENTE COMUNICACAO",
  "ASSISTENTE CONTABIL", "ASSISTENTE COORD JURIDICA", "ASSISTENTE DE DIRECAO", "ASSISTENTE DE PESQUISA",
  "ASSISTENTE DE PLANEJAMENTO E CONTROLE", "ASSISTENTE DE PROJETOS", "ASSISTENTE DIRETORIA", "ASSISTente DIRETORIA EXECUTIVO PL",
  "ASSISTENTE DIRETORIA JR", "ASSISTENTE DIRETORIA PL", "ASSISTENTE DIRETORIA SR", "ASSISTENTE EVENTOS",
  "ASSISTENTE FINANCEIRO", "ASSISTENTE GERENCIA", "ASSISTENTE IMPRENSA", "ASSISTENTE MARKETING",
  "ASSISTENTE MEDICO EXECUTIVO I", "ASSISTENTE PESQUISA", "ASSISTENTE PESQUISA CLINICA", "ASSISTENTE PESQUISA JR",
  "ASSISTENTE PLAN CONTROLE I", "ASSISTENTE PLAN ORCAM FINANC I", "ASSISTENTE RECURSOS HUMANOS",
  "ASSISTENTE RELACOES INTERNACIONAIS", "ASSISTENTE SAUDE SUPLEMENTAR", "ASSISTENTE SOCIAL",
  "ASSISTENTE TECNICO DIRECAO I", "ASSISTENTE TECNICO DIRECAO II", "ASSISTENTE TECNICO DIRECAO III",
  "ASSISTENTE TECNICO DIRECAO IV", "ASSISTENTE TECNICO HUMANIZACAO I", "ASSISTENTE TECNICO HUMANIZACAO JR",
  "ASSISTENTE TECNICO SAUDE I", "ASSISTENTE TECNICO SAUDE II", "ASSISTENTE TECNICO SAUDE III", "ATENDENTE DE NUTRICAO",
  "ATENDENTE ENFERMAGEM", "ATENDENTE NUTRICAO", "ATENDENTE ODONTOLOGICO", "AUDITOR MEDICO", "AUXILIAR ADMINISTRATIVO",
  "AUXILIAR ALMOXARIFADO", "AUXILIAR ATENDIMENTO HOSPITALAR", "AUXILIAR BIBLIOTECARIO", "AUXILIAR CONTABIL",
  "AUXILIAR CRECHE", "AUXILIAR DE ALMOXARIFADO", "AUXILIAR DE ATENDIMENTO", "AUXILIAR DE BIBLIOTECA E DOCUMENTACAO",
  "AUXILIAR DE BIOTERIO", "AUXILIAR DE COLETA", "AUXILIAR DE COMPRAS", "AUXILIAR DE CONSULTORIO ODONTOLOGICO",
  "AUXILIAR DE ENFERMAGEM", "AUXILIAR DE FARMACIA", "AUXILIAR DE LABORATORIO", "AUXILIAR DE MANUTENCAO",
  "AUXILIAR DE PESSOAL", "AUXILIAR DE RADIOLOGIA", "AUXILIAR DE RECURSOS HUMANOS", "AUXILIAR DE SAUDE",
  "AUXILIAR DE SERVICOS GERAIS", "AUXILIAR DESENVOLVIMENTO INFANTIL", "AUXILIAR ENFERMAGEM", "AUXILIAR ESCRITORIO",
  "AUXILIAR FATURAMENTO HOSPITALAR", "AUXILIAR FINANCEIRO", "AUXILIAR INFORMATICA", "AUXILIAR JURIDICO",
  "AUXILIAR LABORATORIO", "AUXILIAR MANUTENCAO GERAL", "AUXILIAR PATRIMONIO", "AUXILIAR SAUDE BUCAL",
  "AUXILIAR SERVICOS", "AUXILIAR SERVICOS GERAIS", "AUXILIAR SERVICOS SAUDE", "AUXILIAR SUPORTE",
  "AUXILIAR TECNICO SAUDE", "BIBLIOTECARIO", "BIOLOGISTA", "BIOLOGISTA CHEFE", "BIOLOGISTA ENCARREGADO", "BIOMEDICO",
  "BIOMEDICO IMAGEM", "CAIXA", "CAMAREIRO", "CHEFE DE GABINETE DE AUTARQUIA", "CHEFE DE SAUDE I",
  "CHEFE DE SECAO DE HEMODINAMICA", "CHEFE GABINETE AUTARQUIA", "CHEFE I", "CHEFE II", "CHEFE SECAO",
  "CHEFE SECAO TECNICA", "CIRURGIAO DENTISTA", "COMPRADOR JR", "COMPRADOR PL", "COMPRADOR SENIOR", "CONSULTOR",
  "CONSULTOR EDUCACAO MEDICA", "CONTADOR CHEFE", "COORDENADOR", "COORDENADOR ADM PROJETOS", "COORDENADOR ADMINISTRATIVO",
  "COORDENADOR AREA", "COORDENADOR ASSISTENCIA SOCIAL", "COORDENADOR AUDITORIA MEDICA", "COORDENADOR CAPACITACAO SR",
  "COORDENADOR COMPRAS", "COORDENADOR COMUNICAO SR", "COORDENADOR CONDICIONAMENTO FISICO", "COORDENADOR CONTABIL",
  "COORDENADOR DA QUALIDADE", "COORDENADOR DE ALMOXARIFADO", "COORDENADOR DE AREA", "COORDENADOR DE CONTAS A PAGAR",
  "COORDENADOR DE CURSOS", "COORDENADOR DE ENFERMAGEM", "COORDENADOR DE ESTUDO", "COORDENADOR DE INFORMATICA",
  "COORDENADOR DE NUCLEO", "COORDENADOR DE OBRAS", "COORDENADOR DE PESQUISA", "COORDENADOR DE PROJETOS",
  "COORDENADOR ED. PERMANENTE", "COORDENADOR EDUCACIONAL", "COORDENADOR ENFERMAGEM I",
  "COORDENADOR ENFERMAGEM PESQ. CLINICA", "COORDENADOR EXECUTIVO", "COORDENADOR FARMACEUTICO ONCOLOGICO",
  "COORDENADOR FARMACIA", "COORDENADOR FINANCEIRO", "COORDENADOR FISCAL", "COORDENADOR FISIOTERAPIA",
  "COORDENADOR FONOAUDIOLOGIA", "COORDENADOR MARKETING", "COORDENADOR MEDICO", "COORDENADOR MEDICO OS",
  "COORDENADOR MEDICO SERV. ESPEC. 3", "COORDENADOR MEDICO SERV/ESPECIALIDADE", "COORDENADOR MEDICO TI",
  "COORDENADOR NUTRIÇÃO", "COORDENADOR OBRAS ENG CIVIL", "COORDENADOR OBRAS ENG CIVIL/CALC ESTR",
  "COORDENADOR ODONTOLOGIA", "COORDENADOR OPERACOES SR", "COORDENADOR PEDAGOGICO", "COORDENADOR PESQUISA JR",
  "COORDENADOR PESQUISA MEDICA", "COORDENADOR PESQUISA PL", "COORDENADOR PROJETOS", "COORDENADOR PROJETOS PL",
  "COORDENADOR PROJETOS SR", "COORDENADOR PSICOLOGIA", "COORDENADOR RELACIONAMENTO", "COORDENADOR SERVICO SOCIAL",
  "COORDENADOR TECNOLOGIA INFORMACAO SR", "COORDENADOR TERAPIA OCUPACIONAL", "COPEIRA", "COPEIRA ENCARREGADO",
  "COZINHEIRO", "COZINHEIRO CHEFE", "DESIGNER GRAFICO", "DESINSETIZADOR", "DIRETOR", "DIRETOR DE COORDENACAO",
  "DIRETOR DE DIVISAO", "DIRETOR DE LABORATORIO", "DIRETOR DE SERVICO", "DIRETOR DE UNIDADE", "DIRETOR EXECUTIVO",
  "DIRETOR EXECUTIVO PROGRAMA", "DIRETOR FINANCEIRO", "DIRETOR I", "DIRETOR II", "DIRETOR PRESIDENTE",
  "DIRETOR PROAHSA", "DIRETOR SERVICOS", "DIRETOR TECNICO DE SAUDE I", "DIRETOR TECNICO DE SAUDE II",
  "DIRETOR TECNICO DE SAUDE III", "DIRETOR TECNICO DEPARTAMENTO", "DIRETOR TECNICO DEPARTAMENTO (MED)",
  "DIRETOR TECNICO DEPARTAMENTO SAUDE", "DIRETOR TECNICO DIVISAO SAUDE (ENF)", "DIRETOR TECNICO I", "DIRETOR TECNICO II",
  "DIRETOR TECNICO III", "DIRETOR TECNICO SERVICO", "DIRETOR TECNICO SERVICO SAUDE (ENF)",
  "DIRETOR TECNICO SERVICO SAUDE (MED)", "DOSIMETRISTA", "EDUCADOR SAUDE PUBLICA ENCARREGADO",
  "ENCARREGADO ADMINISTRATIVO", "ENCARREGADO DE SAUDE I", "ENCARREGADO I", "ENCARREGADO II", "ENCARREGADO OPERACOES",
  "ENCARREGADO SERVICOS GERAIS", "ENCARREGADO SETOR", "ENCARREGADO SETOR DE INFRAESTRUTURA", "ENFERMEIRO",
  "ENFERMEIRO AUDITOR", "ENFERMEIRO CHEFE", "ENFERMEIRO DO TRABALHO", "ENFERMEIRO EDUCACAO CONTINUADA",
  "ENFERMEIRO ENCARREGADO", "ENFERMEIRO PESQUISA", "ENFERMEIRO TRABALHO", "ENGENHEIRO", "ENGENHEIRO (CICLOTRON)",
  "ENGENHEIRO CLINICO", "ENGENHEIRO DE AUTOMACAO", "ENGENHEIRO DE SEGURANCA DO TRABALHO", "ENGENHEIRO I", "ENGENHEIRO IV",
  "ENGENHEiro MANUTENCAO", "ENGENHEIRO OBRAS I", "ENGENHEIRO SEGURANCA TRABALHO", "ENGENHEIRO V", "ENGENHEIRO VI",
  "ERGONOMISTA", "ESCRITURARIO", "ESPECIALISTA CONTABIL", "ESPECIALISTA EM PESQUISA/APOIO MUSEU",
  "ESPECIALISTA EM PROJETOS PL", "ESPECIALISTA EM PROJETOS PMO PL", "ESTAGIARIO", "ESTAGIARIO CIEE", "EXECUTIVO PUBLICO",
  "FARMACEUTICO", "FARMACEUTICO CHEFE", "FARMACEUTICO ENCARREGADO", "FARMACEUTICO JR", "FARMACEUTICO ONCOLOGICO",
  "FARMACEUTICO PL", "FATURISTA", "FISICO", "FISICO JR (CICLOTRON)", "FISICO SR (CICLOTRON)", "FISIOLOGISTA",
  "FISIOTERAPEUTA", "FISIOTERAPEUTA CHEFE", "FONOAUDIOLOGO", "FONOAUDIOLOGO CHEFE", "GERENTE 1", "GERENTE ACADEMICO",
  "GERENTE ADMINISTRATIVO", "GERENTE ADMINISTRATIVO FINANCEIRO", "GERENTE CENTRO CIRURGICO", "GERENTE COMERCIAL",
  "GERENTE DE ADMINISTRACAO DE OBRAS", "GERENTE DE COMUNICACAO", "GERENTE DE FATURAMENTO", "GERente de inovação",
  "GERENTE DE PRODUTOS", "GERENTE DE PROJETOS", "GERENTE DE PROJETOS DE PESQUISA", "GERENTE DE QUALIDADE RISCO ASSIST.",
  "GERENTE DE RECURSOS HUMANOS", "GERENTE EDUCACIONAL", "GERENTE ENFERMAGEM", "GERENTE EXECUTIVO",
  "GERENTE EXECUTIVO FMUSP", "GERENTE FINANCEIRO", "GERENTE II RAD (ICESP)", "GERENTE JURIDICO", "GERENTE MEDICO",
  "GERENTE MULTI PROFISSIONAL", "GERENTE OPERAÇOES", "GERENTE PESQUISA E INOVACAO", "GERENTE PROJETOS PL",
  "GERENTE PROJETOS SR", "GERENTE RADIOLOGIA", "GERENTE T.I", "GERENTE TECNOLOGIA DA INFORMACAO", "GESTOR PROJETOS",
  "GESTOR PROJETOS I", "INSTRUMENTADOR CIRURGICO", "INSTRUTOR DE LIBRAS", "INTERPRETE DE LIBRAS", "JOVEM APRENDIZ",
  "MECANICO MANUTENCAO", "MEDICO", "MEDICO ANESTESIOLOGISTA", "MEDICO ASSISTENTE", "MEDICO ASSISTENTE I",
  "MEDICO ASSISTENTE IV", "MEDICO CARDIOLOGISTA", "MEDICO CIRURGIAO CARDIOVASCULAR", "MEDICO CIRURGIAO TORACICO",
  "MEDICO CLINICO", "MEDICO EM DIAGNOSTICO POR IMAGEM", "MEDICO EM MEDICINA NUCLEAR", "MEDICO ENSINO PESQUISA",
  "MEDICO GENETICISTA", "MEDICO HEMATOLOGISTA", "MEDICO I", "MEDICO II", "MEDICO III", "MEDICO INFECTOLOGISTA",
  "MEDICO INFORMATA JR", "MEDICO LITO/ENDO", "MEDICO NUTROLOGISTA", "MEDICO OBSTETRA", "MEDICO PATOLOGISTA",
  "MEDICO PLANTONISTA", "MEDICO PNEUMOLOGISTA", "MEDICO PRECEPTOR", "MEDICO PSIQUIATRA", "MEDICO PSIQUIATRA I",
  "MEDICO PSIQUIATRA II", "MEDICO SUPERVISOR", "MEDICO TRABALHO ASSISTENCIAL", "MEDICO VETERINARIO",
  "MONITOR DE PESQUISA JUNIOR", "MONITOR EDUCACIONAL", "MONITOR PESQUISA CLINICA JR", "MONITOR PESQUISA CLINICA PL",
  "MONTADOR EVENTOS", "MOTORISTA", "NUTRICIONISTA", "NUTRICIONISTA CHEFE", "NUTRICIONISTA ENCARREGADO", "OFFICE BOY",
  "OFICIAL ADMINISTRATIVO", "OFICIAL OPERACIONAL", "OFICIAL SERVICOS MANUTENCAO", "OFICIAL SOCIOCULTURAL",
  "OPERADOR AUDIO/VIDEO", "OPERADOR DE TELEATENDIMENTO", "OPERADOR MICRO PL", "OPERADOR TERMINAL",
  "OPERADOR TERMINAL COMPUTADOR", "ORTOPTISTA", "OUVIDOR", "OUVIDOR (IPER)", "PERFUSIONISTA", "PESQUISADOR",
  "PESQUISADOR ASSISTENTE", "PESQUISADOR CIENTIFICO II", "PESQUISADOR CIENTIFICO III", "PESQUISADOR CIENTIFICO V",
  "PESQUISADOR CIENTIFICO VI", "PESQUISADOR II", "PESQUISADOR III", "PESQUISADOR JR", "PESQUISADOR PL", "PINTOR",
  "PORTEIRO", "PROCURADOR DE AUTARQUIA NIVEL V", "PROFESSOR DE EDUCACAO FISICA", "PROGRAMADOR JR", "PROGRAMADOR PL",
  "PROGRAMADOR SR", "PSICOLOGO", "PSICOLOGO CHEFE", "PSICOPEDAGOGO", "RECEPCIONISTA", "RECREACIONISTA",
  "RELACOES PUBLICAS", "ROUPEIRO", "SECRETARIA EXECUTIVA", "SECRETARIA PL", "SECRETARIO", "SERVENTE LABORATORIO",
  "SERVICAL DE LABORATORIO", "SERVICAL LABORATORIO", "SUPERINTENDENTE", "SUPERINTENDENTE DE PROJETOS ESPECIAIS",
  "SUPERINTENDENTE GERAL", "SUPERV ANALISE E AUDITORIA DE GLOSA", "SUPERVISOR", "SUPERVISOR AREA HOSPITALAR",
  "SUPERVISOR COMERCIAL", "SUPERVISOR DE ADMINISTRACAO DE INFORMACAO", "SUPERVISOR DE AREA HOSPITALAR",
  "SUPERVISOR DE COMPRAS", "SUPERVISOR DE CONTAS MEDICAS", "SUPERVISOR DE DESENVOVIMENTO DE SISTEMAS",
  "SUPERVISOR DE DIVISAO HOSPITALAR", "SUPERVISOR DE SAUDE", "SUPERVISOR DE SECAO HOSPITALAR",
  "SUPERVISOR DE SERVICO HOSPITALAR", "SUPERVISOR DE SETOR HOSPITALAR", "SUPERVISOR ENGENHARIA CLINICA",
  "SUPERVISOR PESQUISA CLINICA", "SUPERVISOR SECAO HOSPITALAR", "SUPERVISOR SERVICO HOSPITALAR", "SUPERVISOR SISTEMAS",
  "SUPERVISOR SUPORTE TECNICO", "SUPERVISOR TECNICO (MED)", "SUPERVISOR TECNICO I", "TECNICO DE BIOMECANICA II",
  "TÉCNICO DE BIOTÉRIO", "TECNICO DE EDIFICACOES", "TECNICO DE ELETROCARDIOGRAMA", "TECNICO DE ELETROENCEFALOGRAMA",
  "TECNICO DE ELETRONICA", "TECNICO DE ENFERMAGEM", "TECNICO DE ENFERMAGEM DO TRABALHO", "TECNICO DE INFORMATICA",
  "TECNICO DE INSTRUMENTACAO", "TECNICO DE LABORATORIO", "TECNICO DE METODOS GRAFICOS", "TECNICO DE NECROPSIA",
  "TECNICO DE NUTRICAO", "TECNICO DE PESQUISA", "TECNICO DE PLANEJAMENTO E CONTROLE",
  "TECNICO DE PROVAS DE FUNCAO PULMONAR", "TECNICO DE RADIOLOGIA", "TECNICO DE SEGURANCA DO TRABALHO",
  "TECNICO ELETRONICA", "TECNICO EM DESIGNER GRAFICO 3D", "TECNICO EM FARMACIA", "TECNICO EM MIDIAS INTERATIVAS",
  "TECNICO EM NUTRICAO", "TECNICO ENFERMAGEM", "TECNICO ENFERMAGEM TRABALHO", "TECNICO EQUIPAMENTOS MEDICOS",
  "TECNICO ESPECIALIZADO EM PESQUISA", "TECNICO HIGIENE BUCAL", "TECNICO LABORATORIO", "TECNICO METODOS GRAFICOS",
  "TECNICO OFICINA TERAPEUTICA", "TECNICO ORTESE E PROTESE JR", "TECNICO ORTESE E PROTESE PL",
  "TECNICO ORTESE E PROTESE SR", "TECNICO QUIMICO (CICLOTRON)", "TECNICO RADIOLOGIA", "TECNICO REABILITACAO FISICA",
  "TECNICO REDE EMENDADOR", "TECNICO SEGURANCA TRABALHO", "TECNICO SUPORTE JR", "TECNICO SUPORTE PL",
  "TECNICO SUPORTE SR", "TECNOLOGO", "TECNOLOGO EM GESTAO AMBIENTAL", "TECNOLOGO EM IMAGEM",
  "TECNOLOGO EM IMAGEM CHEFE", "TECNOLOGO I", "TECNOLOGO IMAGEM", "TECNOLOGO MECANICO PL", "TECNOLOGO SAUDE",
  "TERAPEUTA OCUPACIONAL", "VIGIA", "WEB DESIGN", "Outro"
];


export const INSTITUTOS_CONFIG: Record<Instituto, InstitutoConfig> = {
  "ICHC": { name: "ICHC", fullName: "Instituto Central", logo: "/hc/ICHC.png", color: "bg-blue-500" },
  "InCor": { name: "InCor", fullName: "Instituto do Coração", logo: "/hc/InCor.png", color: "bg-red-500" },
  "IOT": { name: "IOT", fullName: "Inst. de Ortopedia e Traumatologia", logo: "/hc/IOT.png", color: "bg-green-500" },
  "IPQ": { name: "IPQ", fullName: "Instituto de Psiquiatria", logo: "/hc/IPQ.png", color: "bg-purple-500" },
  "InRad": { name: "InRad", fullName: "Instituto de Radiologia", logo: "/hc/InRad.png", color: "bg-yellow-500" },
  "ICr": { name: "ICr", fullName: "Inst. da Criança e do Adolescente", logo: "/hc/ICr.png", color: "bg-pink-500" },
  "ICESP": { name: "ICESP", fullName: "Instituto do Câncer de SP", logo: "/hc/ICESP.png", color: "bg-indigo-500" },
  "IMREA": { name: "IMREA", fullName: "Inst. de Medicina Física e Reabilitação", logo: "/hc/IMREA.png", color: "bg-teal-500" },
  "LIMs": { name: "LIMs", fullName: "Labs. de Investigação Médica", logo: "/hc/LIMs.png", color: "bg-gray-500" },
  "IPer": { name: "IPer", fullName: "Instituto Perdizes", logo: "/hc/IPer.png", color: "bg-orange-500" },
  "IGS": { name: "IGS", fullName: "Instituto de Gestão e Saúde", logo: "/hc/IGS.png", color: "bg-cyan-500" },
  "Outros": { name: "Outros", fullName: "Outro Instituto", logo: "/hc/ICHC.png", color: "bg-slate-500" },
};